### ISSUE TITLE
Wrong colliders size from LDTk level

### ISSUE THREAD

**Issue by rbouar** [443eb9/bevy_entitiles#12]
Hello,
I'm experiencing a bug with the automatic colliders creation, see images.

This how I use `LdtkPhysicsLayer`:
```rust
        .insert_resource(LdtkAdditionalLayers {
            physics_layer: Some(LdtkPhysicsLayer {
                identifier: "PhysicsColliders".to_string(),
                air: 0,
                parent: "Collisions".to_string(),
                tiles: Some(HashMap::from([(
                    1,
                    PhysicsTile {
                        rigid_body: true,
                        friction: Some(0.9),
                    },
                )])),
            }),
            ..Default::default()
        })
```

The bottom wall and the left wall have wrong collider size:
![in_game](https://github.com/443eb9/bevy_entitiles/assets/30211667/6c43b931-9591-4991-a673-b77aa0a8b61d)
![in_ldtk](https://github.com/443eb9/bevy_entitiles/assets/30211667/dc58753b-793b-44c0-9783-9975153e8ee5)

## Dependencies
```toml
[dependencies]
bevy = "0.12"
bevy_entitiles = {version = "0.4.0", features = ["ldtk", "physics"]}
bevy_xpbd_2d = "0.3.3"
bevy_entitiles_derive = "0.3.0"
bevy-inspector-egui = "0.22.1"
```

## System information
- cargo version: 1.75.0
- `SystemInfo { os: "Linux 24.05 NixOS", kernel: "6.6.10", cpu: "12th Gen Intel(R) Core(TM) i5-12400", core_count: "6", memory: "15.4 GiB" }`
- `AdapterInfo { name: "AMD Radeon RX 6500 XT", vendor: 4098, device: 29759, device_type: DiscreteGpu, driver: "AMD open-source driver", driver_info: "2023.Q4.2 (LLPC)", backend: Vulkan }`
